### ISSUE TITLE
Bug: 댓글에 ' ' (공백) 만 넣고 작성을 누르면 페이지가 제대로 안 보입니다.

### ISSUE THREAD

**Issue by jhm1313** [wafflestudio19-5/team5-web#44]
![image](https://user-images.githubusercontent.com/44698831/148635564-90bdc1c6-b531-4ec8-adc3-3469914900fa.png)

이 상태로 작성 누르면,

![image](https://user-images.githubusercontent.com/44698831/148635568-d06d75c8-f2b7-498e-b078-da4fd884f41e.png)

여기서 다음 페이지로 안 넘어갑니다.

**Comment by mgahn0706** [comment]
" "만 입력 시 빈 댓글로 인식하도록 했습니다 감사합니다!!
