### ISSUE TITLE
Bug: 대댓글 작성자가 틀리게 뜨는 오류

### ISSUE THREAD

**Issue by gyuuuna** [wafflestudio19-5/team5-web#49]
특정 댓글에 대하여 대댓글을 작성할 때, 작성자가 현재 로그인한 유저 본인으로 뜨는 것이 아니라 해당 댓글의 작성자와 같게 뜹니다.
해당 댓글 작성자와 대댓글 작성자가 다른 유저여도 그러하며, 익명 체크 여부도 적용되지 않습니다.

![image](https://user-images.githubusercontent.com/86581647/148644288-020763c5-7bb4-499e-ab72-ecc9ef56fe02.png)
여기에서 익명1이 처음에 단 것으로 뜨는 댓글은 제가 쓴 것이 아니며, 이에 대한 대댓글은 제가 쓴 것입니다.
또한 익명 체크를 하고 대댓글을 써도 적용되지 않고 댓글 작성자와 같게 뜹니다.
새로운 댓글 작성의 경우 잘 구현되었습니다.

**Comment by mgahn0706** [comment]
수정했습니다! 이상한 실수를 했군요.. 감사합니다!
